In [26]:
import socket
import time

HOST = '127.0.0.1'  # Standard loopback interface address (localhost)
PORT = 65432        # Port to listen on (non-privileged ports are > 1023)
import numpy as np 
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    conn, addr = s.accept()
    val = np.array([1,1,1,1])
    with conn:
        print('Connected by', addr)
        startTime = time.time()
        while True:
            startTime = time.time()
            val +=1
            conn.sendall(f'{val[0]} {val[1]} {val[2]} {val[3]}\n'.encode())
            print(val)
            data = conn.recv(1024)
            if not data:
                break
            print(data, "\n")


Connected by ('127.0.0.1', 42720)
[2 2 2 2]
b'20.0 0.0 ' 

[3 3 3 3]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 ' 

[4 4 4 4]
b'20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[5 5 5 5]
b'20.0 0.0 ' 

[6 6 6 6]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 ' 

[7 7 7 7]
b'20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[8 8 8 8]
b'20.0 0.0 ' 

[9 9 9 9]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[10 10 10 10]
b'20.0 0.0 ' 

[11 11 11 11]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[89 89 89 89]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[90 90 90 90]
b'20.0 0.0 ' 

[91 91 91 91]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[92 92 92 92]
b'20.0 0.0 ' 

[93 93 93 93]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[94 94 94 94]
b'20.0 0.0 ' 

[95 95 95 95]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0

b'20.0 0.0 ' 

[167 167 167 167]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[168 168 168 168]
b'20.0 0.0 ' 

[169 169 169 169]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[170 170 170 170]
b'20.0 0.0 ' 

[171 171 171 171]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[172 172 172 172]
b'20.0 0.0 ' 

[173 173 173 173]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[249 249 249 249]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 19.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[250 250 250 250]
b'20.0 0.0 ' 

[251 251 251 251]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 19.0 75.0 19.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[252 252 252 252]
b'20.0 0.0 ' 

[253 253 253 253]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 19.0 75.0 18.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[254 254 254 254]
b'20.0 0.0 ' 

[255 255 255 255]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 19.0 75.0 18.

b'20.0 0.0 ' 

[315 315 315 315]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[316 316 316 316]
b'20.0 0.0 ' 

[317 317 317 317]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[318 318 318 318]
b'20.0 0.0 ' 

[319 319 319 319]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[320 320 320 320]
b'20.0 0.0 ' 

[321 321 321 321]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[391 391 391 391]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 10.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[392 392 392 392]
b'20.0 0.0 ' 

[393 393 393 393]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 10.0 150.0 11.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[394 394 394 394]
b'20.0 0.0 ' 

[395 395 395 395]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 10.0 150.0 10.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[396 396 396 396]
b'20.0 0.0 ' 

[397 397 397 397]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[469 469 469 469]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[470 470 470 470]
b'20.0 0.0 ' 

[471 471 471 471]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[472 472 472 472]
b'20.0 0.0 ' 

[473 473 473 473]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[474 474 474 474]
b'20.0 0.0 ' 

[475 475 475 475]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[543 543 543 543]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[544 544 544 544]
b'20.0 0.0 ' 

[545 545 545 545]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[546 546 546 546]
b'20.0 0.0 ' 

[547 547 547 547]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[548 548 548 548]
b'20.0 0.0 ' 

[549 549 549 549]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[623 623 623 623]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[624 624 624 624]
b'20.0 0.0 ' 

[625 625 625 625]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[626 626 626 626]
b'20.0 0.0 ' 

[627 627 627 627]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[628 628 628 628]
b'20.0 0.0 ' 

[629 629 629 629]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[705 705 705 705]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[706 706 706 706]
b'20.0 0.0 ' 

[707 707 707 707]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[708 708 708 708]
b'20.0 0.0 ' 

[709 709 709 709]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[710 710 710 710]
b'20.0 0.0 ' 

[711 711 711 711]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[785 785 785 785]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[786 786 786 786]
b'20.0 0.0 ' 

[787 787 787 787]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[788 788 788 788]
b'20.0 0.0 ' 

[789 789 789 789]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[790 790 790 790]
b'20.0 0.0 ' 

[791 791 791 791]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

[874 874 874 874]
b'20.0 0.0 ' 

[875 875 875 875]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[876 876 876 876]
b'20.0 0.0 ' 

[877 877 877 877]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[878 878 878 878]
b'20.0 0.0 ' 

[879 879 879 879]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[880 880 880 880]
b'20.0 0.0 ' 

[881 881 881 881]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 

b'20.0 0.0 ' 

[957 957 957 957]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[958 958 958 958]
b'20.0 0.0 ' 

[959 959 959 959]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[960 960 960 960]
b'20.0 0.0 ' 

[961 961 961 961]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[962 962 962 962]
b'20.0 0.0 ' 

[963 963 963 963]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.

b'20.0 0.0 ' 

[1039 1039 1039 1039]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1040 1040 1040 1040]
b'20.0 0.0 ' 

[1041 1041 1041 1041]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1042 1042 1042 1042]
b'20.0 0.0 ' 

[1043 1043 1043 1043]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1044 1044 1044 1044]
b'20.0 0.0 ' 

[1045 1045 1045 1045]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1123 1123 1123 1123]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 11.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1124 1124 1124 1124]
b'20.0 0.0 ' 

[1125 1125 1125 1125]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 12.0 150.0 15.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1126 1126 1126 1126]
b'20.0 0.0 ' 

[1127 1127 1127 1127]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 12.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1128 1128 1128 1128]
b'20.0 0.0 ' 

[1129 1129 1129 1129]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1205 1205 1205 1205]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 17.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1206 1206 1206 1206]
b'20.0 0.0 ' 

[1207 1207 1207 1207]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 17.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1208 1208 1208 1208]
b'20.0 0.0 ' 

[1209 1209 1209 1209]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 17.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1210 1210 1210 1210]
b'20.0 0.0 ' 

[1211 1211 1211 1211]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1295 1295 1295 1295]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 6.0 195.0 6.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1296 1296 1296 1296]
b'20.0 0.0 ' 

[1297 1297 1297 1297]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 16.0 180.0 7.0 195.0 7.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1298 1298 1298 1298]
b'20.0 0.0 ' 

[1299 1299 1299 1299]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 18.0 180.0 7.0 195.0 8.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1300 1300 1300 1300]
b'20.0 0.0 ' 

[1301 1301 1301 1301]
b'20.0 15.0 20.0 30.0 20.0 45.0 2

b'20.0 0.0 ' 

[1383 1383 1383 1383]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1384 1384 1384 1384]
b'20.0 0.0 ' 

[1385 1385 1385 1385]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1386 1386 1386 1386]
b'20.0 0.0 ' 

[1387 1387 1387 1387]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1388 1388 1388 1388]
b'20.0 0.0 ' 

[1389 1389 1389 1389]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1467 1467 1467 1467]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 7.0 120.0 9.0 135.0 14.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1468 1468 1468 1468]
b'20.0 0.0 ' 

[1469 1469 1469 1469]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 8.0 120.0 9.0 135.0 16.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1470 1470 1470 1470]
b'20.0 0.0 ' 

[1471 1471 1471 1471]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 8.0 120.0 10.0 135.0 19.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1472 1472 1472 1472]
b'20.0 0.0 ' 

[1473 1473 1473 1473]
b'20.0 15.0 20.0 30.0 20.0 45.0 

b'20.0 0.0 ' 

[1545 1545 1545 1545]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1546 1546 1546 1546]
b'20.0 0.0 ' 

[1547 1547 1547 1547]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1548 1548 1548 1548]
b'20.0 0.0 ' 

[1549 1549 1549 1549]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1550 1550 1550 1550]
b'20.0 0.0 ' 

[1551 1551 1551 1551]
b'20.0 15.0 20.0 30.0 20.0 

[1623 1623 1623 1623]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1624 1624 1624 1624]
b'20.0 0.0 ' 

[1625 1625 1625 1625]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1626 1626 1626 1626]
b'20.0 0.0 ' 

[1627 1627 1627 1627]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1628 1628 1628 1628]
b'20.0 0.0 ' 

[1629 1629 1629 1629]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 

b'20.0 0.0 ' 

[1705 1705 1705 1705]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1706 1706 1706 1706]
b'20.0 0.0 ' 

[1707 1707 1707 1707]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1708 1708 1708 1708]
b'20.0 0.0 ' 

[1709 1709 1709 1709]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1710 1710 1710 1710]
b'20.0 0.0 ' 

[1711 1711 1711 1711]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1791 1791 1791 1791]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1792 1792 1792 1792]
b'20.0 0.0 ' 

[1793 1793 1793 1793]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1794 1794 1794 1794]
b'20.0 0.0 ' 

[1795 1795 1795 1795]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1796 1796 1796 1796]
b'20.0 0.0 ' 

[1797 1797 1797 1797]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[1873 1873 1873 1873]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1874 1874 1874 1874]
b'20.0 0.0 ' 

[1875 1875 1875 1875]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1876 1876 1876 1876]
b'20.0 0.0 ' 

[1877 1877 1877 1877]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1878 1878 1878 1878]
b'20.0 0.0 ' 

[1879 1879 1879 1879]
b'20.0 15.0 20.0 30.0 20.0 

[1963 1963 1963 1963]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1964 1964 1964 1964]
b'20.0 0.0 ' 

[1965 1965 1965 1965]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1966 1966 1966 1966]
b'20.0 0.0 ' 

[1967 1967 1967 1967]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[1968 1968 1968 1968]
b'20.0 0.0 ' 

[1969 1969 1969 1969]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 

b'20.0 0.0 ' 

[2047 2047 2047 2047]
b'20.0 15.0 5.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2048 2048 2048 2048]
b'20.0 0.0 ' 

[2049 2049 2049 2049]
b'20.0 15.0 5.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2050 2050 2050 2050]
b'20.0 0.0 ' 

[2051 2051 2051 2051]
b'20.0 15.0 5.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2052 2052 2052 2052]
b'20.0 0.0 ' 

[2053 2053 2053 2053]
b'20.0 15.0 6.0 30.0 6.0 45.0 

b'20.0 0.0 ' 

[2129 2129 2129 2129]
b'20.0 15.0 20.0 30.0 9.0 45.0 7.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 17.0 315.0 20.0 330.0 20.0 345.0 ' 

[2130 2130 2130 2130]
b'20.0 0.0 ' 

[2131 2131 2131 2131]
b'20.0 15.0 20.0 30.0 8.0 45.0 5.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 17.0 300.0 13.0 315.0 20.0 330.0 20.0 345.0 ' 

[2132 2132 2132 2132]
b'20.0 0.0 ' 

[2133 2133 2133 2133]
b'20.0 15.0 20.0 30.0 8.0 45.0 5.0 60.0 6.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 13.0 300.0 10.0 315.0 10.0 330.0 20.0 345.0 ' 

[2134 2134 2134 2134]
b'20.0 0.0 ' 

[2135 2135 2135 2135]
b'20.0 15.0 20.0 30.0 8.0 45.0 4.0

b'20.0 0.0 ' 

[2219 2219 2219 2219]
b'20.0 15.0 20.0 30.0 9.0 45.0 8.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2220 2220 2220 2220]
b'20.0 0.0 ' 

[2221 2221 2221 2221]
b'20.0 15.0 20.0 30.0 9.0 45.0 8.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2222 2222 2222 2222]
b'20.0 0.0 ' 

[2223 2223 2223 2223]
b'20.0 15.0 20.0 30.0 9.0 45.0 8.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2224 2224 2224 2224]
b'20.0 0.0 ' 

[2225 2225 2225 2225]
b'20.0 15.0 20.0 30.0 9.0 45.0 7.

b'20.0 0.0 ' 

[2309 2309 2309 2309]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2310 2310 2310 2310]
b'20.0 0.0 ' 

[2311 2311 2311 2311]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2312 2312 2312 2312]
b'20.0 0.0 ' 

[2313 2313 2313 2313]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2314 2314 2314 2314]
b'20.0 0.0 ' 

[2315 2315 2315 2315]
b'20.0 15.0 20.0 30.0 20.0 

[2399 2399 2399 2399]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 4.0 165.0 4.0 180.0 1.0 195.0 1.0 210.0 1.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2400 2400 2400 2400]
b'20.0 0.0 ' 

[2401 2401 2401 2401]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 4.0 165.0 5.0 180.0 1.0 195.0 1.0 210.0 1.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2402 2402 2402 2402]
b'20.0 0.0 ' 

[2403 2403 2403 2403]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 5.0 165.0 6.0 180.0 1.0 195.0 1.0 210.0 1.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2404 2404 2404 2404]
b'20.0 0.0 ' 

[2405 2405 2405 2405]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 

b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 7.0 300.0 6.0 315.0 8.0 330.0 20.0 345.0 ' 

[2488 2488 2488 2488]
b'20.0 0.0 ' 

[2489 2489 2489 2489]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 4.0 300.0 5.0 315.0 7.0 330.0 10.0 345.0 ' 

[2490 2490 2490 2490]
b'20.0 0.0 ' 

[2491 2491 2491 2491]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 5.0 300.0 4.0 315.0 5.0 330.0 9.0 345.0 ' 

[2492 2492 2492 2492]
b'20.0 0.0 ' 

[2493 2493 2493 2493]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 2

[2575 2575 2575 2575]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 4.0 165.0 10.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 11.0 315.0 11.0 330.0 20.0 345.0 ' 

[2576 2576 2576 2576]
b'20.0 0.0 ' 

[2577 2577 2577 2577]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 4.0 165.0 9.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 11.0 330.0 20.0 345.0 ' 

[2578 2578 2578 2578]
b'20.0 0.0 ' 

[2579 2579 2579 2579]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 5.0 165.0 7.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 14.0 330.0 20.0 345.0 ' 

[2580 2580 2580 2580]
b'20.0 0.0 ' 

[2581 2581 2581 2581]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 

b'20.0 0.0 ' 

[2665 2665 2665 2665]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 19.0 90.0 19.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2666 2666 2666 2666]
b'20.0 0.0 ' 

[2667 2667 2667 2667]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2668 2668 2668 2668]
b'20.0 0.0 ' 

[2669 2669 2669 2669]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2670 2670 2670 2670]
b'20.0 0.0 ' 

[2671 2671 2671 2671]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[2741 2741 2741 2741]
b'17.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 14.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2742 2742 2742 2742]
b'20.0 0.0 ' 

[2743 2743 2743 2743]
b'17.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 12.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2744 2744 2744 2744]
b'20.0 0.0 ' 

[2745 2745 2745 2745]
b'18.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 12.0 195.0 11.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2746 2746 2746 2746]
b'20.0 0.0 ' 

[2747 2747 2747 2747]
b'19.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[2839 2839 2839 2839]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2840 2840 2840 2840]
b'20.0 0.0 ' 

[2841 2841 2841 2841]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2842 2842 2842 2842]
b'20.0 0.0 ' 

[2843 2843 2843 2843]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2844 2844 2844 2844]
b'20.0 0.0 ' 

[2845 2845 2845 2845]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[2923 2923 2923 2923]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2924 2924 2924 2924]
b'20.0 0.0 ' 

[2925 2925 2925 2925]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2926 2926 2926 2926]
b'20.0 0.0 ' 

[2927 2927 2927 2927]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[2928 2928 2928 2928]
b'20.0 0.0 ' 

[2929 2929 2929 2929]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3013 3013 3013 3013]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3014 3014 3014 3014]
b'20.0 0.0 ' 

[3015 3015 3015 3015]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3016 3016 3016 3016]
b'20.0 0.0 ' 

[3017 3017 3017 3017]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3018 3018 3018 3018]
b'20.0 0.0 ' 

[3019 3019 3019 3019]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3105 3105 3105 3105]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 17.0 195.0 1.0 210.0 1.0 225.0 1.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3106 3106 3106 3106]
b'20.0 0.0 ' 

[3107 3107 3107 3107]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 15.0 195.0 1.0 210.0 1.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3108 3108 3108 3108]
b'20.0 0.0 ' 

[3109 3109 3109 3109]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 14.0 195.0 1.0 210.0 1.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3110 3110 3110 3110]
b'20.0 0.0 ' 

[3111 3111 3111 3111]
b'20.0 15.0 20.0 30.0 20.0 45.0 20

b'20.0 0.0 ' 

[3195 3195 3195 3195]
b'1.0 15.0 1.0 30.0 1.0 45.0 20.0 60.0 20.0 75.0 1.0 90.0 1.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3196 3196 3196 3196]
b'2.0 0.0 ' 

[3197 3197 3197 3197]
b'1.0 15.0 1.0 30.0 1.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3198 3198 3198 3198]
b'1.0 0.0 ' 

[3199 3199 3199 3199]
b'1.0 15.0 1.0 30.0 1.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3200 3200 3200 3200]
b'1.0 0.0 ' 

[3201 3201 3201 3201]
b'1.0 15.0 1.0 30.0 20.0 45.0 20.0 60.0 2

[3270 3270 3270 3270]
b'12.0 0.0 ' 

[3271 3271 3271 3271]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3272 3272 3272 3272]
b'13.0 0.0 ' 

[3273 3273 3273 3273]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3274 3274 3274 3274]
b'15.0 0.0 ' 

[3275 3275 3275 3275]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3276 3276 3276 3276]
b'17.0 0.0 ' 

[3277 3277 3277 3277]
b'20.

b'20.0 0.0 ' 

[3361 3361 3361 3361]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3362 3362 3362 3362]
b'20.0 0.0 ' 

[3363 3363 3363 3363]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3364 3364 3364 3364]
b'20.0 0.0 ' 

[3365 3365 3365 3365]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3366 3366 3366 3366]
b'20.0 0.0 ' 

[3367 3367 3367 3367]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3447 3447 3447 3447]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 12.0 150.0 11.0 165.0 20.0 180.0 12.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3448 3448 3448 3448]
b'20.0 0.0 ' 

[3449 3449 3449 3449]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 12.0 165.0 20.0 180.0 9.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3450 3450 3450 3450]
b'20.0 0.0 ' 

[3451 3451 3451 3451]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 13.0 165.0 20.0 180.0 8.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3452 3452 3452 3452]
b'20.0 0.0 ' 

[3453 3453 3453 3453]
b'20.0 15.0 20.0 30.0 20.0 45

b'20.0 0.0 ' 

[3535 3535 3535 3535]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3536 3536 3536 3536]
b'20.0 0.0 ' 

[3537 3537 3537 3537]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3538 3538 3538 3538]
b'20.0 0.0 ' 

[3539 3539 3539 3539]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3540 3540 3540 3540]
b'20.0 0.0 ' 

[3541 3541 3541 3541]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3617 3617 3617 3617]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3618 3618 3618 3618]
b'20.0 0.0 ' 

[3619 3619 3619 3619]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3620 3620 3620 3620]
b'20.0 0.0 ' 

[3621 3621 3621 3621]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3622 3622 3622 3622]
b'20.0 0.0 ' 

[3623 3623 3623 3623]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3703 3703 3703 3703]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 7.0 195.0 1.0 210.0 1.0 225.0 1.0 240.0 1.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3704 3704 3704 3704]
b'20.0 0.0 ' 

[3705 3705 3705 3705]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 7.0 195.0 2.0 210.0 1.0 225.0 1.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3706 3706 3706 3706]
b'20.0 0.0 ' 

[3707 3707 3707 3707]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 6.0 195.0 1.0 210.0 1.0 225.0 1.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3708 3708 3708 3708]
b'20.0 0.0 ' 

[3709 3709 3709 3709]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.

b'20.0 0.0 ' 

[3789 3789 3789 3789]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3790 3790 3790 3790]
b'20.0 0.0 ' 

[3791 3791 3791 3791]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3792 3792 3792 3792]
b'20.0 0.0 ' 

[3793 3793 3793 3793]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3794 3794 3794 3794]
b'20.0 0.0 ' 

[3795 3795 3795 3795]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3873 3873 3873 3873]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3874 3874 3874 3874]
b'20.0 0.0 ' 

[3875 3875 3875 3875]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3876 3876 3876 3876]
b'20.0 0.0 ' 

[3877 3877 3877 3877]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3878 3878 3878 3878]
b'20.0 0.0 ' 

[3879 3879 3879 3879]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[3965 3965 3965 3965]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3966 3966 3966 3966]
b'20.0 0.0 ' 

[3967 3967 3967 3967]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3968 3968 3968 3968]
b'20.0 0.0 ' 

[3969 3969 3969 3969]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[3970 3970 3970 3970]
b'20.0 0.0 ' 

[3971 3971 3971 3971]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4053 4053 4053 4053]
b'13.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4054 4054 4054 4054]
b'20.0 0.0 ' 

[4055 4055 4055 4055]
b'14.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4056 4056 4056 4056]
b'20.0 0.0 ' 

[4057 4057 4057 4057]
b'14.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4058 4058 4058 4058]
b'20.0 0.0 ' 

[4059 4059 4059 4059]
b'15.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4133 4133 4133 4133]
b'10.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 9.0 135.0 15.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4134 4134 4134 4134]
b'20.0 0.0 ' 

[4135 4135 4135 4135]
b'11.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 6.0 135.0 15.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4136 4136 4136 4136]
b'20.0 0.0 ' 

[4137 4137 4137 4137]
b'12.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 4.0 120.0 4.0 135.0 15.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4138 4138 4138 4138]
b'20.0 0.0 ' 

[4139 4139 4139 4139]
b'13.0 15.0 20.0 30.0 20.0 45.0

b'20.0 0.0 ' 

[4225 4225 4225 4225]
b'20.0 15.0 20.0 30.0 4.0 45.0 1.0 60.0 1.0 75.0 1.0 90.0 1.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 9.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4226 4226 4226 4226]
b'20.0 0.0 ' 

[4227 4227 4227 4227]
b'20.0 15.0 20.0 30.0 3.0 45.0 1.0 60.0 1.0 75.0 1.0 90.0 1.0 105.0 1.0 120.0 20.0 135.0 20.0 150.0 7.0 165.0 8.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4228 4228 4228 4228]
b'20.0 0.0 ' 

[4229 4229 4229 4229]
b'20.0 15.0 20.0 30.0 3.0 45.0 1.0 60.0 1.0 75.0 1.0 90.0 1.0 105.0 1.0 120.0 20.0 135.0 20.0 150.0 5.0 165.0 6.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4230 4230 4230 4230]
b'20.0 0.0 ' 

[4231 4231 4231 4231]
b'20.0 15.0 20.0 30.0 3.0 45.0 1.0 60.0 1.0 75.0 

b'20.0 0.0 ' 

[4315 4315 4315 4315]
b'20.0 15.0 20.0 30.0 4.0 45.0 1.0 60.0 1.0 75.0 2.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 15.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4316 4316 4316 4316]
b'20.0 0.0 ' 

[4317 4317 4317 4317]
b'20.0 15.0 20.0 30.0 4.0 45.0 1.0 60.0 1.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 15.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4318 4318 4318 4318]
b'20.0 0.0 ' 

[4319 4319 4319 4319]
b'20.0 15.0 13.0 30.0 3.0 45.0 2.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 13.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4320 4320 4320 4320]
b'20.0 0.0 ' 

[4321 4321 4321 4321]
b'20.0 15.0 12.0 30.0 3.0 45.0 4.0 6

b'20.0 0.0 ' 

[4401 4401 4401 4401]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4402 4402 4402 4402]
b'20.0 0.0 ' 

[4403 4403 4403 4403]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4404 4404 4404 4404]
b'20.0 0.0 ' 

[4405 4405 4405 4405]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4406 4406 4406 4406]
b'20.0 0.0 ' 

[4407 4407 4407 4407]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4485 4485 4485 4485]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 16.0 135.0 7.0 150.0 7.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4486 4486 4486 4486]
b'20.0 0.0 ' 

[4487 4487 4487 4487]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 15.0 135.0 6.0 150.0 6.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4488 4488 4488 4488]
b'20.0 0.0 ' 

[4489 4489 4489 4489]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 13.0 135.0 5.0 150.0 6.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4490 4490 4490 4490]
b'20.0 0.0 ' 

[4491 4491 4491 4491]
b'20.0 15.0 20.0 30.0 20.0 45.0 2

b'20.0 0.0 ' 

[4579 4579 4579 4579]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4580 4580 4580 4580]
b'20.0 0.0 ' 

[4581 4581 4581 4581]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4582 4582 4582 4582]
b'20.0 0.0 ' 

[4583 4583 4583 4583]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4584 4584 4584 4584]
b'20.0 0.0 ' 

[4585 4585 4585 4585]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4669 4669 4669 4669]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 11.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4670 4670 4670 4670]
b'20.0 0.0 ' 

[4671 4671 4671 4671]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 12.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4672 4672 4672 4672]
b'20.0 0.0 ' 

[4673 4673 4673 4673]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 13.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4674 4674 4674 4674]
b'20.0 0.0 ' 

[4675 4675 4675 4675]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4751 4751 4751 4751]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4752 4752 4752 4752]
b'20.0 0.0 ' 

[4753 4753 4753 4753]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4754 4754 4754 4754]
b'20.0 0.0 ' 

[4755 4755 4755 4755]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4756 4756 4756 4756]
b'20.0 0.0 ' 

[4757 4757 4757 4757]
b'20.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4845 4845 4845 4845]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 13.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4846 4846 4846 4846]
b'20.0 0.0 ' 

[4847 4847 4847 4847]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 13.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4848 4848 4848 4848]
b'20.0 0.0 ' 

[4849 4849 4849 4849]
b'14.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4850 4850 4850 4850]
b'20.0 0.0 ' 

[4851 4851 4851 4851]
b'11.0 15.0 20.0 30.0 20.0 

b'20.0 0.0 ' 

[4929 4929 4929 4929]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4930 4930 4930 4930]
b'20.0 0.0 ' 

[4931 4931 4931 4931]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4932 4932 4932 4932]
b'20.0 0.0 ' 

[4933 4933 4933 4933]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[4934 4934 4934 4934]
b'20.0 0.0 ' 

[4935 4935 4935 4935]
b'20.0 15.0 20.0 30.0 20.0 

[5013 5013 5013 5013]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[5014 5014 5014 5014]
b'20.0 0.0 ' 

[5015 5015 5015 5015]
b'20.0 15.0 20.0 30.0 20.0 45.0 20.0 60.0 20.0 75.0 20.0 90.0 20.0 105.0 20.0 120.0 20.0 135.0 20.0 150.0 20.0 165.0 20.0 180.0 20.0 195.0 20.0 210.0 20.0 225.0 20.0 240.0 20.0 255.0 20.0 270.0 20.0 285.0 20.0 300.0 20.0 315.0 20.0 330.0 20.0 345.0 ' 

[5016 5016 5016 5016]
b'20.0 0.0 ' 

[5017 5017 5017 5017]
b'20.0 15.0 ' 

[5018 5018 5018 5018]
b'20.0 30.0 ' 

[5019 5019 5019 5019]
b'20.0 45.0 ' 

[5020 5020 5020 5020]
b'20.0 60.0 ' 

[5021 5021 5021 5021]
b'20.0 75.0 ' 

[5022 5022 5022 5022]
b'20.0 90.0 ' 

[5023 5023 5023 5023]
b'20.0 105.0 ' 

[5024 5024 5024 5024]
b'20.0 120.0 ' 

[5025 5025 5025 5025]
b'20.0 135.0 ' 

[5026 5026 5026 5026]
b'20.0 15

In [151]:

#!/usr/bin/env python3

import socket

HOST = '127.0.0.1'  # The server's hostname or IP address
PORT = 65432        # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(b'Hello, world')
    data = s.recv(1024)

print('Received', repr(data))

ConnectionRefusedError: [Errno 111] Connection refused